### ISSUE TITLE
Permanant link to css for ezpa.library.ualberta.ca

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/library-cms#391]
After deploying [1.7.13](https://github.com/ualbertalib/library-cms/releases/tag/1.7.13) the css for the ezproxy login page is broken.  For example:  https://ezpa.library.ualberta.ca/ezpAuthen.cgi?url=https://search.ebscohost.com/login.aspx?custid=s5940188&groupid=main&profid=eds&authtype=ip&scope=site&site=eds-live&direct=true&bquery=climate

![image](https://user-images.githubusercontent.com/1220762/190700086-34e2f0f8-6143-4299-8fd9-c4e6fd78e496.png)

Assets are recompiled when a new deploy occurs giving them a new target url.  

E.g. 
Before: https://library.ualberta.ca/packs/css/2020main-b14b8dcf.css
After: https://library.ualberta.ca/packs/css/2020main-42478107.css

Possible solutions
- ensure that applications are self contained
- ensure that assets that are depended on elsewhere have an unchanging target
- combine dependent parts into one application
- are there any significant difference between https://library.ualberta.ca/packs/css/2020main-42478107.css and https://library.ualberta.ca/cms-css/1/2020main.css? If not then cms-css might be an existing solution

**Comment by nmacgreg** [comment]
Yikes, seems we took very careful aim, then deliberately shot off a toe.

**Comment by pgwillia** [comment]
I haven't heard about any further issues.
