### ISSUE TITLE
Add Google Tag Manager code and Meta tag

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/library-cms#561]
- [x] Add Google tag manager to the main layout file (library-cms/app/views/layouts/2020.html.erb). While we have the Google Analytics tag installed, Google Tag Manager allows for more granular analytics - especially click throughs and user flows. Here are the instructions for installing Google Tag Manager:

1. Paste this code as high in the head of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'[https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)](https://www.googletagmanager.com/gtm.js?id=%27+i+dl;f.parentNode.insertBefore(j,f));
})(window,document,'script','dataLayer','GTM-PVV4HQM4');</script>

2. Paste this code immediately after the opening body tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVV4HQM4"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

- [ ] Add a meta line to the same file (library-cms/app/views/layouts/2020.html.erb) which would allow us to choose if we want a page to not be crawled by robots. I believe the line should be <meta name="robots" content="<%= cms:text meta %>">. However, this is the change that I would want to test in a dev environment before committing. It might be that the line should be <meta name="robots" content="<%= yield(:meta) %>">. This will then give us the option of adding a "noindex" content attribute from within the cms. To test if this is working you would go into the CMS frontend, create a test page, choose the "non-rich-text-noindex" layout, add noindex into the meta field, publish the page and then check that the <meta name="robots" content="noindex"> is in the header of that page.

**Comment by pgwillia** [comment]
@nnunn, there is urgency for the first task to add Google Tag Manager, but not the second to add the ability to "noindex" individual pages.  Is that right?

**Comment by nnunn** [comment]
Yes that is right - we would like to have the Google Tag Manager installed as soon as possible, but the "noindex" change can wait for as long as needed.

Thanks!
